feat: rework variables and add more functionality
brendangeck/semantic-release-kaniko pull request #11
Opened 2024-08-14 12:54 UTC by syphernl

- Reworked the parameters, they can either be set in the plugin or via env. This makes it easier to configure in CI
  - Added support for `--target` to target a specific stage of the container to build
  - Added support for `--cache` and `--cache-ttl` to use transparant Kaniko cache
  - Added support for providing an alternative Kaniko directory (as it breaks building images that contain Kaniko in `/kaniko/executor`)
  - Simplified the required parameters for creating the registry URI, only the registry + image is now used, `project` seemed redundant

2024-08-14 15:50 UTC, brendangeck requested changes
Thank you so much for being the first contributor other than me to the repo! I've left some simple comments

2024-08-14 15:50 UTC, brendangeck commented on lib/verifyConditions.mjs
> +    MISSING_TAGS: 'Missing image tags in configuration',
I see you removed the `project` in favor of just the `image` parameter. This unfortunately will not be a backwards compatible change and may break our current users (I'm aware of a few people already using this plugin 👀 )

I think we should add it back in.

2024-08-14 15:50 UTC, brendangeck commented on lib/publish.mjs
> +    const kanikoDir = pluginConfig.kanikoDir || process.env.KANIKO_DIR;
Could we move this parsing logic to a separate function? It does clutter this publish function quite a bit.

2024-08-14 15:50 UTC, brendangeck commented on lib/publish.mjs
> +            if (cache) kanikoArgs.push('--cache=true'); // Enable cache if specified
nit: Does this need to follow the '=' convention?

2024-08-14 15:50 UTC, brendangeck commented on lib/verifyConditions.mjs
> +    const dockerfilePath = pluginConfig.dockerfile || process.env.DOCKER_FILE || 'Dockerfile';
This is duplicate parsing logic from the public class. Is there any way we can unify this input parsing? Possibly in just some simple utilities function?

2024-08-15 06:20 UTC, syphernl commented on lib/publish.mjs
> +    const kanikoDir = pluginConfig.kanikoDir || process.env.KANIKO_DIR;
Agreed! I moved this parsing logic.

2024-08-15 06:20 UTC, syphernl commented on lib/verifyConditions.mjs
> +    const dockerfilePath = pluginConfig.dockerfile || process.env.DOCKER_FILE || 'Dockerfile';
Done!

2024-08-15 06:32 UTC, syphernl commented on lib/verifyConditions.mjs
> +    MISSING_TAGS: 'Missing image tags in configuration',
The `project` parameter is only used to generate an image name, adding it back in seems pretty redundant. Especially for a project that is only a few days old and is bound to have breaking changes at some point 😉 
Either way; I added in some logic to handle this. If `project` is given it will be prepended to the `image`, otherwise the `image` variable is used (without `project` prepended).  Does that make sense?

2024-08-15 15:37 UTC, brendangeck commented on lib/verifyConditions.mjs
> +    MISSING_TAGS: 'Missing image tags in configuration',
That’s perfect

2024-08-15 15:39 UTC, brendangeck approved these changes

2024-08-15 18:50 UTC, brendangeck commented
Approved! Only issue is that the integ tests are failing. This was an issue I experienced with the ES5 vs CommonJS imports, and I was able to solve this by [manually importing including the file extension](https://github.com/syphernl/semantic-release-kaniko/blob/feat/enhance/index.mjs) (see the file extensions included in the import).

Additionally, I believe one of our integ tests can be removed now that PROJECT is an optional field: https://github.com/syphernl/semantic-release-kaniko/blob/feat/enhance/tst/integ/verifyConditions.test.js#L44-L54

2024-08-16 19:23 UTC, brendangeck commented
After thinking more about it, I agree with your opinion that project is an unecessary parameter, and it's too early to worry about backwards compatibility. I've gone ahead and updated your code to do the following:
- Remove project param
- Add additional check for setting cache TTL in kaniko args
- Adding kanikoDir to config parsing
- Updating tests
- Updating README

2024-08-16 19:24 UTC, merged